### ISSUE TITLE
PG::ConnectionBad PQconsumeInput() connection not open

### ISSUE THREAD

**Issue by aaronjensen** [ged/ruby-pg#441]
Ever since #431 we have been seeing this error more:

```
PG::ConnectionBad PQconsumeInput() connection not open
```

Our particular setup is prone to connection issues (connections go unused for hours sometimes and when the thing wakes up, we get some sort of issue). But this particular one is new and it's happening in the `block` after the line changed in #431. It's usually `PG::UnableToSend SSL SYSCALL error: EOF detected` we see. We do intend to correct our connection handling to not hold onto idle connections for so long. I just want to make sure that this isn't a new problem.

Can you think of a reason why we'd see this more now?

Thanks!

**Comment by larskanis** [comment]
Shrug! I fixed another issue in pg-1.3.4, which was introduced in pg-1.3.0: c76b123bf2103707208148ef8cb7313d3b8ede34 Maybe it's related although the error is different.

Did you find out something more?

**Comment by aaronjensen** [comment]
Nothing more yet. I actually just saw a rash of `Errno::EBADF: Bad file descriptor` on our services this morning after upgrading to 1.3.4. I don't think I've seen those before.

```
PG::UnableToSend: SSL SYSCALL error: EOF detected

  from pg/connection.rb:313:in `exec'
  from pg/connection.rb:313:in `transaction'
```

The `PQconsumeInput() connection not open` are still happening as well.

I'm hoping that it all has to do with Azure's flaky network and our keeping idle connections open for hours on end.

**Comment by aaronjensen** [comment]
The `Errno::EBADF: Bad file descriptor` are happening a lot more often than any of the other similar connection issues we've seen.

**Comment by larskanis** [comment]
Do you have a stack trace of the `Errno::EBADF: Bad file descriptor`?

We had this error in production with pg-1.3.0 to pg-1.3.3 in conjunction with kerberos authentication. It is now fixed with pg-1.3.4. So I wonder that the opposite seems to happen on your side.

**Comment by aaronjensen** [comment]
Those were all the relevant lines, but here is the full trace. I believe that one of these was an inner exception, not sure which.

```
PG::UnableToSend: SSL SYSCALL error: EOF detected

  from pg/connection.rb:313:in `exec'
  from pg/connection.rb:313:in `transaction'
  from message_store/postgres/session.rb:137:in `transaction'
  from message_store/postgres/write.rb:23:in `write'
  from message_store/write.rb:55:in `call'
  from messaging/write.rb:62:in `call'
  from consumer/postgres/position_store.rb:50:in `put'
  from consumer/position_store.rb:82:in `put'
  from consumer/consumer.rb:141:in `update_position'
  from consumer/consumer.rb:127:in `dispatch'
  from consumer/actor.rb:63:in `block in <class:Actor>'
  from actor/module/handler.rb:18:in `call'
  from actor/module/handler.rb:18:in `handle'
  from actor/module/handler/send_next_message.rb:6:in `handle'
  from actor/module/suspend_resume/handle.rb:11:in `handle'
  from actor/module/run_loop.rb:8:in `block in run_loop'
  from actor/module/run_loop.rb:5:in `loop'
  from actor/module/run_loop.rb:5:in `run_loop'
  from actor/start.rb:32:in `block in call'

Errno::EBADF: Bad file descriptor
  from pg/connection.rb:317:in `block'
  from pg/connection.rb:317:in `rescue in transaction'
  from pg/connection.rb:312:in `transaction'
  from message_store/postgres/session.rb:137:in `transaction'
  from message_store/postgres/write.rb:23:in `write'
  from message_store/write.rb:55:in `call'
  from messaging/write.rb:62:in `call'
  from consumer/postgres/position_store.rb:50:in `put'
  from consumer/position_store.rb:82:in `put'
  from consumer/consumer.rb:141:in `update_position'
  from consumer/consumer.rb:127:in `dispatch'
  from consumer/actor.rb:63:in `block in <class:Actor>'
  from actor/module/handler.rb:18:in `call'
  from actor/module/handler.rb:18:in `handle'
  from actor/module/handler/send_next_message.rb:6:in `handle'
  from actor/module/suspend_resume/handle.rb:11:in `handle'
  from actor/module/run_loop.rb:8:in `block in run_loop'
  from actor/module/run_loop.rb:5:in `loop'
  from actor/module/run_loop.rb:5:in `run_loop'
  from actor/start.rb:32:in `block in call'
```

**Comment by larskanis** [comment]
@aaronjensen Did you manage to find the root cause for the ConnectionBad error? Can the issue be closed?

**Comment by aaronjensen** [comment]
I don’t know the root cause, but they are connections that are idle for potentially hours. Keep alive seems to not be sufficient for them. We do plan to recycle connections after some idle time we just haven’t done it yet. 

We can close this though as it is likely a network and/or config issue on our end.
